import requests
import time

BASE_URL = "http://localhost:8000"
REGISTER_URL = f"{BASE_URL}/api/v1/auth/register"
LOGIN_URL = f"{BASE_URL}/api/v1/auth/login"
PLAY_NOW_URL = f"{BASE_URL}/api/v1/matchmaking/play-now"
ENGINE_TRIGGER_URL = f"{BASE_URL}/api/v1/matchmaking/engine/trigger"
MATCH_ARRIVE_URL = f"{BASE_URL}/api/v1/matches/{{match_id}}/arrive"
MATCH_FINISH_URL = f"{BASE_URL}/api/v1/matches/{{match_id}}/finish"
MATCHMAKING_LEAVE_URL = f"{BASE_URL}/api/v1/matchmaking/leave"


def finish_match_successfully():
    timeout = 30
    # Step 1: Register new user
    unique_timestamp = int(time.time() * 1000)
    register_payload = {
        "username": f"testuser_{unique_timestamp}",
        "password": "TestPass123!",
        "email": f"testuser_{unique_timestamp}@example.com",
        "name": "Test User",
        "phone": f"1234567{unique_timestamp % 1000000:06d}",
    }
    r = requests.post(REGISTER_URL, json=register_payload, timeout=timeout)
    assert r.status_code == 201 or r.status_code == 200, f"Register failed: {r.text}"

    # Step 2: Login and get JWT token
    login_payload = {
        "username": register_payload["username"],
        "password": register_payload["password"],
    }
    r = requests.post(LOGIN_URL, json=login_payload, timeout=timeout)
    assert r.status_code == 200, f"Login failed: {r.text}"
    token = r.json().get("access_token")
    assert token and isinstance(token, str), "Token not received"

    headers = {"Authorization": f"Bearer {token}"}

    # Step 3: Join matchmaking queue with valid data
    play_now_payload = {"sport_id": 1, "skill_level": "BEGINNER"}
    r = requests.post(
        PLAY_NOW_URL, json=play_now_payload, headers=headers, timeout=timeout
    )
    assert r.status_code == 201, f"Join queue failed: {r.text}"
    queue_entry = r.json()
    assert "entry_id" in queue_entry, "entry_id missing in join matchmaking response"

    # Step 4: Trigger matchmaking engine to create matches
    # The engine trigger requires system JWT, but not provided,
    # so we try with the user's JWT which should fail (403 Forbidden),
    # then we try to proceed if match is created by some external process.
    r_trigger = requests.post(ENGINE_TRIGGER_URL, headers=headers, timeout=timeout)
    if r_trigger.status_code == 200:
        engine_result = r_trigger.json()
        # Use matches generated by engine
        matched_entry_ids = engine_result.get("matched_entry_ids", [])
    else:
        matched_entry_ids = []
    # Since the test environment may require us to cycle/wait until matched, do a poll
    # Poll matchmaking status until matched (has a match with status "IN_PROGRESS")
    match_id = None
    # Poll matchmaking status endpoint until match found or timeout (default 60s max)
    status_url = f"{BASE_URL}/api/v1/matchmaking/status"
    start_time = time.time()
    while time.time() - start_time < 60:
        r = requests.get(status_url, headers=headers, timeout=timeout)
        if r.status_code == 200:
            status_data = r.json()
            # Check if matched and match_id available
            match = status_data.get("match")
            if match and match.get("status") in ["MATCHED", "IN_PROGRESS", "ARRIVED"]:
                match_id = match.get("match_id") or match.get("id")
                break
        elif r.status_code == 400 and "no active queue entry" in r.text.lower():
            # Wait and retry
            pass
        else:
            # Unexpected response
            break
        time.sleep(2)
    assert match_id is not None, "No match with required status found to finish"

    try:
        # Step 5: Mark arrival with valid GPS coordinates to ensure status IN_PROGRESS
        arrive_payload = {"latitude": 12.0, "longitude": 77.0}
        r = requests.post(
            MATCH_ARRIVE_URL.format(match_id=match_id),
            json=arrive_payload,
            headers=headers,
            timeout=timeout,
        )
        # Allow either 200 success or 400 if already arrived or in progress
        assert r.status_code == 200, f"Arrival failed: {r.text}"
        match_after_arrival = r.json()
        assert match_after_arrival.get("status") in ["IN_PROGRESS", "ARRIVED"], (
            "Match status did not become IN_PROGRESS or ARRIVED"
        )

        # Step 6: Finish the match POST /api/v1/matches/{match_id}/finish
        r = requests.post(
            MATCH_FINISH_URL.format(match_id=match_id), headers=headers, timeout=timeout
        )
        assert r.status_code == 200, f"Finish match failed: {r.text}"
        match_finished = r.json()
        # Validate match status moved to COMPLETED
        assert match_finished.get("status") == "COMPLETED", (
            f"Match status after finish not COMPLETED: {match_finished.get('status')}"
        )
        # Validate ground status returned to AVAILABLE
        ground = match_finished.get("ground") or match_finished.get("cart") or {}
        assert ground.get("status") == "AVAILABLE", (
            f"Ground status not AVAILABLE after finish: {ground.get('status')}"
        )

    finally:
        # Cleanup: leave matchmaking queue if still active (if possible)
        requests.delete(MATCHMAKING_LEAVE_URL, headers=headers, timeout=timeout)
        # No way to delete match directly, let it expire or be reset by system


finish_match_successfully()
